### ISSUE TITLE
Functional and component specification feedback

### ISSUE THREAD

**Issue by elmisback** [emilysellinger/Phoenix.github.io#1]
* Functional
    * Problem being addressed
        * Understanding how birds were impacted by the 2020 Oregon wildfires by relating air quality and bird observation data 
    * Data sources, data structure
        * Oregon eBird data (Jan - Nov 2020)
        * Oregon air quality records (hourly)
    * Users: domain, skills, programming experience
        * Ecological researchers -- background in R, not Python
        * recreational birders, citizen scientists, and Audubon societies
    * At least 2 use cases
        * "As an ecological researcher, I want to understand the influence of air quality on different bird species"
        * "As a birder, I'm curious about how air quality affects how likely I am to see a bird in a particular area"
* Component
    * 3+ software components: what it does, inputs it requires, and outputs it provides.
        * These look clear to me.
        * ("Interactions" should describe how the software components interact with each other for the use case.)
    * Preliminary plan
        * Looks good! Remember to prioritize unit tests, proper style, and documentation.

**Comment by zoer27** [comment]
Updated the interactions as well as the components in our component specification, so hopefully the description of how the components interact is clearer.
